services:
  - type: web
    name: ai-creators-studio--viral-1
    runtime: python
    repo: https://github.com/skyboss878/ai-creators-studio--viral
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FLASK_ENV
        sync: false
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeployTrigger: commit
    rootDir: backend
